
module.exports={
  weixin:{
    appID:"xxxxxxx",
    appSecret:"xxxxxx",
    token:"xxxxxx",
    menueData:{
      button:[
        {
          type:"click",
          key:"getInfo",
          name:"获取消息",
          sub_button:[
            {
              type:"click",
              name:"文字消息",
              key:"text"
            },
            {
              type:"click",
              name:"图片消息",
              key:"image"
            },
            {
              type:"click",
              name:"图文消息",
              key:"news"
            },
            {
              type:"click",
              name:"获取语音",
              key:"music"
            }
          ]
        },
        {
          type:"click",
          key:"uploadInfo",
          name:"请回复",
          sub_button:[
            {
              type:"pic_photo_or_album",
              name:"图片",
              key:"sysImage"
            },
            {
              type:"location_select",
              name:"发送您的位置",
              key:"locat"
            }
          ]
        },
        {
          type:"click",
          key:"other",
          name:"其他",
          sub_button:[
            {
              type:"view",
              name:"搜索",
              url:"https://www.baidu.com"
            }
          ]
        }
      ]
    }
  }
}
